name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build (Release)
        run: make
      
      - name: Build (Debug)
        run: make debug
      
      - name: Run tests
        run: make test
