name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: signal-demo

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      # 메뉴에 "7\n"을 주입해서 auto_test만 돌리고,
      # 60초 넘으면 timeout이 강제로 끊어서 무한 대기/실패 방지
      - name: Run auto_test non-interactively (60s timeout)
        run: |
          printf "7\n" | timeout 60s ./signal_demo
